title: 这是一个标题
author: SolinLee
email: solinlee18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这是一个github使用介绍制作的.使用主题的demo

# social links
github_username: solinlee

show_excerpts: true 

theme: jekyll-theme-to minima
